Numerical Methods TP1

In [1]:
# Imports
import numpy as np
import matplotlib.pyplot as plt

EXERCICE 1

In [30]:
#QUESTION 1
x = np.array([4,6,2,5,8])

#all entries
print(x)

#all entries except first and last
Nn_first = x[1:]
Nn_last = x[:-1]
print(Nn_first, Nn_last)

#every second entry, starting with first and entries at reverse order
sliced_array = x[0::2]
back = x[::-1]
print(sliced_array, back)

#selection with indeces
chosen_ind = x[[0,2,4]]

#last element
last = x[-1]
print(chosen_ind, "\n", last)

#sequence wiht np arrange and np linspace
seq = np.arange(2, 12, 2)
lspace = np.linspace(0, 1, 11)
print(seq, lspace, "\n")


#Question 2
E = np.array([
    [2,4,1,5],
    [6,7,2,1],
    [3,5,8,9]
])

print(E, "\n")

#vectro x1 and matrix y
X1 = E[:, 1]
Y = E[:, [1,3]]
print(X1,"\n", Y)

#sum of each columns/rows
sum_c = E.sum(axis=0)
sum_r = E.sum(axis=1)
print('\n', sum_c, sum_r)

#shapes of E X1 and Y
sh_E = E.shape
sh_x1 = X1.shape
sh_Y = Y.shape
print('\n', sh_E, sh_x1, sh_Y)

#zero matrix
Z = np.zeros((3,4))
print("n",Z)




[4 6 2 5 8]
[6 2 5 8] [4 6 2 5]
[4 2 8] [8 5 2 6 4]
[4 2 8] 
 8
[ 2  4  6  8 10] [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 

[[2 4 1 5]
 [6 7 2 1]
 [3 5 8 9]] 

[4 7 5] 
 [[4 5]
 [7 1]
 [5 9]]

 [11 16 11 15] [12 16 25]

 (3, 4) (3,) (3, 2)
n [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
#Question 3
x = np.array([1, 4, 8])
y = np.array([2, 1, 5])

A = np.array([
    [3, 1, 6],
    [5, 2, 7]
])

R = np.vstack((x, y))
C = np.column_stack((x,y))

# addition for x and y then x to A
print("\n" ,x+y, "\n","\n", x+A)

print("\n", x.T + y , "\n", x.T + A, "\n")

# subtract R from A and subtract 3 from every entry of A
print(A - R)
print(A - 3, "\n")

#Multiply x and y element by element, then divide x by y element by element.
#Multiply A and R element by element.
print(x * y)
print(x / y)
print(A * R, "\n")

#Compute the matrix products AC and AR. Explain why one fails.
print(A @ C)
#print(A @ R)  # error: incompatible dimensions
#number of columns of the first matrix must equal the number of rows of the second matrix


 [ 3  5 13] 
 
 [[ 4  5 14]
 [ 6  6 15]]

 [ 3  5 13] 
 [[ 4  5 14]
 [ 6  6 15]] 

[[ 2 -3 -2]
 [ 3  1  2]]
[[ 0 -2  3]
 [ 2 -1  4]] 

[ 2  4 40]
[0.5 4.  1.6]
[[ 3  4 48]
 [10  2 35]] 

[[55 37]
 [69 47]]
